nohup: ignoring input
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "./u2net_for_atten_preprocess/train_multi_GPU.py", line 9, in <module>
Traceback (most recent call last):
  File "./u2net_for_atten_preprocess/train_multi_GPU.py", line 9, in <module>
    from my_dataset import HSI_Segmentation, HSI_Transformer, HSI_Transformer_all
  File "/data/chaoyi_he/HSI/EC_dataset/u2net_for_atten_preprocess/my_dataset.py", line 2, in <module>
    from my_dataset import HSI_Segmentation, HSI_Transformer, HSI_Transformer_all
  File "/data/chaoyi_he/HSI/EC_dataset/u2net_for_atten_preprocess/my_dataset.py", line 2, in <module>
        import scipy.io as sioimport scipy.io as sio

ModuleNotFoundErrorModuleNotFoundError: : No module named 'scipy'No module named 'scipy'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1060513) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/grads/c/chaoyi_he/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/grads/c/chaoyi_he/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/grads/c/chaoyi_he/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/grads/c/chaoyi_he/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/grads/c/chaoyi_he/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/grads/c/chaoyi_he/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./u2net_for_atten_preprocess/train_multi_GPU.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-27_09:53:59
  host      : ecen-l1s7gxdxvm.engr.tamu.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1060514)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-27_09:53:59
  host      : ecen-l1s7gxdxvm.engr.tamu.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1060513)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
